require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TiposDeGastoController do

  # This should return the minimal set of attributes required to create a valid
  # TipoDeGasto. As you add validations to TipoDeGasto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "detalle" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TiposDeGastoController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tipos_de_gasto as @tipos_de_gasto" do
      tipo_de_gasto = TipoDeGasto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tipos_de_gasto).should eq([tipo_de_gasto])
    end
  end

  describe "GET show" do
    it "assigns the requested tipo_de_gasto as @tipo_de_gasto" do
      tipo_de_gasto = TipoDeGasto.create! valid_attributes
      get :show, {:id => tipo_de_gasto.to_param}, valid_session
      assigns(:tipo_de_gasto).should eq(tipo_de_gasto)
    end
  end

  describe "GET new" do
    it "assigns a new tipo_de_gasto as @tipo_de_gasto" do
      get :new, {}, valid_session
      assigns(:tipo_de_gasto).should be_a_new(TipoDeGasto)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipo_de_gasto as @tipo_de_gasto" do
      tipo_de_gasto = TipoDeGasto.create! valid_attributes
      get :edit, {:id => tipo_de_gasto.to_param}, valid_session
      assigns(:tipo_de_gasto).should eq(tipo_de_gasto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TipoDeGasto" do
        expect {
          post :create, {:tipo_de_gasto => valid_attributes}, valid_session
        }.to change(TipoDeGasto, :count).by(1)
      end

      it "assigns a newly created tipo_de_gasto as @tipo_de_gasto" do
        post :create, {:tipo_de_gasto => valid_attributes}, valid_session
        assigns(:tipo_de_gasto).should be_a(TipoDeGasto)
        assigns(:tipo_de_gasto).should be_persisted
      end

      it "redirects to the created tipo_de_gasto" do
        post :create, {:tipo_de_gasto => valid_attributes}, valid_session
        response.should redirect_to(TipoDeGasto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipo_de_gasto as @tipo_de_gasto" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoDeGasto.any_instance.stub(:save).and_return(false)
        post :create, {:tipo_de_gasto => { "detalle" => "invalid value" }}, valid_session
        assigns(:tipo_de_gasto).should be_a_new(TipoDeGasto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoDeGasto.any_instance.stub(:save).and_return(false)
        TipoDeGasto.any_instance.stub(:errors).and_return('anything')
        post :create, {:tipo_de_gasto => { "detalle" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipo_de_gasto" do
        tipo_de_gasto = TipoDeGasto.create! valid_attributes
        # Assuming there are no other tipos_de_gasto in the database, this
        # specifies that the TipoDeGasto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TipoDeGasto.any_instance.should_receive(:update_attributes).with({ "detalle" => "MyString" })
        put :update, {:id => tipo_de_gasto.to_param, :tipo_de_gasto => { "detalle" => "MyString" }}, valid_session
      end

      it "assigns the requested tipo_de_gasto as @tipo_de_gasto" do
        tipo_de_gasto = TipoDeGasto.create! valid_attributes
        put :update, {:id => tipo_de_gasto.to_param, :tipo_de_gasto => valid_attributes}, valid_session
        assigns(:tipo_de_gasto).should eq(tipo_de_gasto)
      end

      it "redirects to the tipo_de_gasto" do
        tipo_de_gasto = TipoDeGasto.create! valid_attributes
        put :update, {:id => tipo_de_gasto.to_param, :tipo_de_gasto => valid_attributes}, valid_session
        response.should redirect_to(tipo_de_gasto)
      end
    end

    describe "with invalid params" do
      it "assigns the tipo_de_gasto as @tipo_de_gasto" do
        tipo_de_gasto = TipoDeGasto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoDeGasto.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipo_de_gasto.to_param, :tipo_de_gasto => { "detalle" => "invalid value" }}, valid_session
        assigns(:tipo_de_gasto).should eq(tipo_de_gasto)
      end

      it "re-renders the 'edit' template" do
        tipo_de_gasto = TipoDeGasto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoDeGasto.any_instance.stub(:save).and_return(false)
        TipoDeGasto.any_instance.stub(:errors).and_return('anything')
        put :update, {:id => tipo_de_gasto.to_param, :tipo_de_gasto => { "detalle" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipo_de_gasto" do
      tipo_de_gasto = TipoDeGasto.create! valid_attributes
      expect {
        delete :destroy, {:id => tipo_de_gasto.to_param}, valid_session
      }.to change(TipoDeGasto, :count).by(-1)
    end

    it "redirects to the tipos_de_gasto list" do
      tipo_de_gasto = TipoDeGasto.create! valid_attributes
      delete :destroy, {:id => tipo_de_gasto.to_param}, valid_session
      response.should redirect_to(tipos_de_gasto_url)
    end
  end

end
